<?php
/**
 * @file
 * Sourcepoint module.
 */

/**
 * Implements hook_theme().
 */
function sourcepoint_theme($existing, $type, $theme, $path) {
  return [
    'sourcepoint_cmp_overlay' => [
      'variables' => [
        'height' => NULL,
        'width' => NULL,
        'url' => NULL,
      ],
    ],
  ];
}

/**
 * @todo move into service.
 */
function sourcepoint_get_privacy_manager_url() {
  return '';
}

/**
 * @todo move into service.
 */
function sourcepoint_get_privacy_manager_overlay() {
  return '';
}
