sourcepoint.settings:
  type: config_object
  label: 'Sourcepoint settings'
  mapping:
    account_id:
      type: text
      label: 'Account ID'
    enabled:
      type: integer
      label: 'Enabled'
    rid_enabled:
      type: integer
      label: 'RID Enabled'
    content_control_url:
      type: text
      label: 'Content Control URL'
    cmp_enabled:
      type: integer
      label: 'CMP Enabled'
    cmp_site_id:
      type: text
      label: 'Site ID'
    cmp_privacy_manager_id:
      type: text
      label: 'Privacy Manager ID'
    cmp_overlay_height:
      type: text
      label: 'CMP Overlay height'
    cmp_overlay_width:
      type: text
      label: 'CMP Overlay width'
    dtm_enabled:
      type: integer
      label: 'DTM enabled'
    dtm_timeout:
      type: string
      label: 'DTM Timeout'
    style_manager_enabled:
      type: integer
      label: 'Style Manager Enabled'
    mms_domain:
      type: text
      label: 'MMS Domain'
sourcepoint.endpoints.*:
  type: config_entity
  label: 'Sourcepoint Endpoint'
  mapping:
    path:
      type: string
      label: 'Path'
